architecture: arm
entry_point: 0x8000db5
exit_at:
  SetSysClock_fail: 0x8001d7c
  _exit: 0x800060d
  error: 0x80026f1
  mbed_assert_internal: 0x8002541
  mbed_die: 0x80003d9
  mbed_error: 0x8002735
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_MOTE_L152RC.yml
initial_sp: 0x20008000
memory_map:
  text:
    base_addr: 0x8000000
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
