include:
  - ./../../../configs/hw/cortexm_memory.yml

architecture: arm
base_address: 0
entry_point: 0x6C81
initial_sp: 0x20400000

use_nvic: False
use_timers: False

memory_map:
  text: {base_addr: 0x0, file: ./basic_excercises.bin,
    permissions: r-x, size: 0x800000}