include:
  - ./../../../configs/hw/cortexm_memory.yml

architecture: arm
entry_point: 0x08003011
initial_sp: 0x20014000

use_nvic: False
use_timers: False

memory_map:
  ivt: {base_addr: 0x00000000, file: ./basic_excercises.bin,
    permissions: r-x, size: 0x800000}
  text: {base_addr: 0x08000000, file: ./basic_excercises.bin,
    permissions: r-x, size: 0x800000}