architecture: arm
entry_point: 0x800ba7c
exit_at:
  _exit: 0x800ba4d
  error_0: 0x8007809
  error_1: 0x800d4c9
  mbed_assert_internal: 0x800d469
  mbed_die: 0x800b62d
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_wycinwyc.yml
initial_sp: 0x20014000
memory_map:
  text:
    base_addr: 0x8000000
    file: ./expat_panda.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
