include:
  - ./../../../configs/hw/cortexm_memory.yml

architecture: arm
entry_point: 0x402E55
initial_sp: 0x20800000

use_nvic: False
use_timers: False

memory_map:
  ivt: {base_addr: 0x0, file: ./basic_excercises_ivt.bin,
    permissions: r-x, size: 0x40000}
  text: {base_addr: 0x400000, file: ./basic_excercises_text.bin,
    permissions: rwx, size: 0x00800000}
  ZBT_SSRAM23: { base_addr: 0x20400000, permissions: rwx, size: 0x00400000 }