include:
  - ./../../../configs/hw/cortexm_memory.yml

architecture: arm
base_address: 0
entry_point: 0x30C9
initial_sp: 0x10007FE0

use_nvic: False
use_timers: False

memory_map:
  text: {base_addr: 0x0, file: ./basic_excercises.bin,
    permissions: r-x, size: 0x800000}
  main_ram: {base_addr: 0x10000000, permissions: rwx, size: 0x8000} 