architecture: arm
entry_point: 0x8000e51
exit_at:
  _exit: 0x8000649
  error: 0x8002765
  mbed_assert_internal: 0x800257d
  mbed_die: 0x8000419
  mbed_error: 0x80027a9
fuzzed_irqs:
  normal_irqs: 32-33,40-45
  systick: 0xf
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_NUCLEO_L152RE.yml
initial_sp: 0x20014000
memory_map:
  text:
    base_addr: 0x8000000
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
nvic:
  addr: 0x8000000
use_timers: false
