include:
  - ./../../../configs/hw/cortexm_memory.yml

architecture: arm
entry_point: 0x3595
initial_sp: 0x20004000

use_nvic: False
use_timers: False

memory_map:
  text: {base_addr: 0x0, file: ./basic_excercises.bin,
    permissions: r-x, size: 0x800000}