architecture: arm
entry_point: 0x11c5
exit_at:
  _exit: 0x6d1
  mbed_assert_internal: 0x16b5
  mbed_die: 0x4ad
  mbed_error: 0x1c21
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_UBLOX_C027.yml
initial_sp: 0x10007fe0
memory_map:
  sram:
    base_addr: 0x10000000
    permissions: rwx
    size: 0x8000
  text:
    base_addr: 0x0
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
