architecture: arm
entry_point: 0x8001009
exit_at:
  _exit: 0x80006e1
  error: 0x8002209
  mbed_assert_internal: 0x8002081
  mbed_die: 0x80004b1
  mbed_error: 0x800224d
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_NUCLEO_F103RB.yml
initial_sp: 0x20005000
memory_map:
  text:
    base_addr: 0x8000000
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
