architecture: arm
entry_point: 0xac1
exit_at:
  _exit: 0x529
  error: 0x1815
  mbed_assert_internal: 0x120d
  mbed_die: 0x311
  mbed_error: 0x1859
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_MAX32600MBED.yml
initial_sp: 0x20008000
memory_map:
  text:
    base_addr: 0x0
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
mmio_models:
  constant:
    SysTick_ctr_and_status:
      addr: 0xe000e010
      val: 0x10000
  linear:
    SysTick_curr_val:
      addr: 0xe000e018
      step: -0x1000
  passthrough:
    SysTick_reload_val:
      addr: 0xe000e014
use_nvic: false
use_timers: false
