architecture: arm
entry_point: 0x1e05
exit_at:
  _exit: 0x1369
  error: 0x2779
  mbed_assert_internal: 0x2591
  mbed_die: 0x10e5
  mbed_error: 0x27bd
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_EFM32GG_STK3700.yml
initial_sp: 0x20020000
memory_map:
  mmio_information:
    base_addr: 0xfe00000
    permissions: rw-
    size: 0x9000
  text:
    base_addr: 0x0
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
#mmio_models:
#  linear:
#    ticker:
#      addr: 0x40010024
#      init_val: 0x0
#      step: 0xea60
use_nvic: false
use_timers: false
