architecture: arm
entry_point: 0x8001009
exit_at:
  _exit: 0x80007dd
  error: 0x8002435
  mbed_assert_internal: 0x800224d
  mbed_die: 0x80005a9
  mbed_error: 0x8002479
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_NUCLEO_F207ZG.yml
initial_sp: 0x20020000
memory_map:
  text:
    base_addr: 0x8000000
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
