architecture: arm
entry_point: 0xadd
exit_at:
  _exit: 0x4e5
  error: 0x139d
  mbed_assert_internal: 0xeb9
  mbed_die: 0x2d1
include:
- ./../../../configs/hw/cortexm_memory.yml
- ./mmio_model_config_LPC1549.yml
initial_sp: 0x2004000
memory_map:
  mmio_GPIO_USB_CRC_SCTIMER_PWM:
    base_addr: 0x1c000000
    permissions: rw
    size: 0x28000
  sram:
    base_addr: 0x2000000
    permissions: rwx
    size: 0x8000
  text:
    base_addr: 0x0
    file: ./basic_exercises.bin
    permissions: r-x
    size: 0x800000
use_nvic: false
use_timers: false
